---
title: "Calculating the Effective Capture Areas for Case Study A"
---

``` {r installing and loading packages used for analysis}

package.list=c("readr", "dplyr", "janitor", "data.table", "tidyr", "stats",
               "conflicted", "lubridate", "lme4", "pROC", "MuMIn", "caret",
               "mosaic", "mgcv", "gamm4", "insight", "ROCR", "gamclass", "devtools",
               "gammit", "gratia", "gridExtra")

for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}

#devtools::install_github("m-clark/gammit")
library(gammit)
```

```{r, combining two different field data sets}

#bringing in the two processed jog-test data frames for Case Study A
march <- read.csv("../output/march22_det.csv", header=T, na.strings="")
fall <- read.csv("../output/fall22_detect.csv", header=T, na.strings="")

#march DF has an extra, unnecessary column. Removing
march <- select(march, -c(duration.y))

#cleaning up my messy column names to combine the two trials 
names(march)[names(march) == "detection.y"] <- "detection"
names(fall)[names(fall) == "Decection"] <- "detection"

names(march)[names(march) == "detection.datetime"] <- "detection_datetime"
names(march)[names(march) == "seconds.in"] <- "seconds_in"

names(march)[names(march) == "Unique.ID"] <- "unique_id"
names(fall)[names(fall) == "Unique.ID"] <- "unique_id"

names(fall)[names(fall) == "x_distance.y"] <- "x_distance"

names(march)[names(march) == "run_dist.y"] <- "run_dist"
names(march)[names(march) == "x_distance.y"] <- "x_distance"
names(march)[names(march) == "duration.y"] <- "duration"
names(march)[names(march) == "velocity.y"] <- "velocity"
names(march)[names(march) == "grid.dist"] <- "grid_dist"

#merging two trials into one DF
GAMM_df <- rbind(march, fall)
```

```{r, merging jog-test with cover data}

#adding environmental (temperature + cover covariates) collected at each camera
cover <- read.csv("../data/cover.csv", header=T, na.strings="")

#merge
GAMM.df <- right_join(GAMM_df, cover, by = "unique_id", suffix = c("", ""))

#structure variables
str(GAMM.df)
GAMM.df$detection <- as.factor(GAMM.df$detection)
GAMM.df$unique_id <- as.factor(GAMM.df$unique_id)
GAMM.df$brand <- as.factor(GAMM.df$brand)

#Not necessary, but standardizing grid so camera is at location [0,0]. Set bounds from [-10,10] instead of [0,20]
GAMM.df$grid_dist <- (GAMM.df$grid_dist - 10)

#rounding data to nearest whole numbers
GAMM.df$velocity <- round(GAMM.df$velocity, 0)
GAMM.df$grid_dist <- round(GAMM.df$grid_dist, 0)

#saving data frame needed for analysis
#rmnp_GAMM <- write_csv(GAMM.df, "studyA_ADA.csv")
```

```{r, testing and controlling for the refractory peroid}
#minimum time between photographs in our tests was 1 second, mean 2.3. So test to see if photo in previous 1 or 2 seconds influences capture area 
GAMM.df <- arrange(GAMM.df, unique_id, detection_datetime)

#Determine if a trigger happened 1 or 2 seconds ago (2 sec delay with cam)
laggy1 <- (shift(GAMM.df$detection, n = 1, type = 'lag'))
laggy2 <- (shift(GAMM.df$detection, n = 2, type = 'lag'))

#put in df
lag <- cbind.data.frame(laggy1, laggy2)

#numeric 
lag$laggy1 <- as.numeric(lag$laggy1)
lag$laggy2 <- as.numeric(lag$laggy2)

#replace na's with 0
lag$laggy1 <- replace_na(lag$laggy1, 0)
lag$laggy2 <- replace_na(lag$laggy2, 0)

#convert 1's to 0 and 2's to 1 
lag$laggy1[lag$laggy1 == 1] <- 0
lag$laggy2[lag$laggy2 == 1] <- 0

lag$laggy1[lag$laggy1 == 2] <- 1
lag$laggy2[lag$laggy2 == 2] <- 1

#new column with both 
lag$lag <- lag$laggy1 + lag$laggy2

#final step, 2's back to 1's
lag$lag[lag$lag == 2] <- 1

#adding to the pp_GAMM dataframe
GAMM.df$seconds_since <- lag$lag

#formatting 
GAMM.df$seconds_since <- as.factor(GAMM.df$seconds_since)
```

```{r, using Generalized Additive Mixed Models to model probabiltiy of capture in jogged cells}
#fit splines on parallel and perpendicular distances in front of cameras,
#we adjusted 'k' by running model and looking at the effective degrees of 
#freedom in the output. k=6 allowed for most optimal non-linearity

total_mod <- gam(detection ~ s(x_distance, grid_dist, bs='gp') #Gaussian process spline on physical locations infront of camera (equivalent to kriging to allow for interpolation inbetween transects we jogged on)
                + te(shrub, cover) #tensor product spline (interation) for vegetation height and cover
                + brand + temp + velocity + seconds_since #categoriesm temperature, and velocity as standard GLM variables 
                + s(unique_id, bs='fs'), # factor smooth for random effect, allows variable curvature for each level 
                 data = GAMM.df, family = 'binomial') 

#model output
gratia::draw(total_mod)
summary(total_mod)

#model checks 
gam.check(total_mod) #passes checks. Need to check if residual assumptions are met

#saving GAMM model for ADA calculations later.
#ADA_gamm <- save(total_mod, file = "ADA_gamm.Rdata") 
```

```{r, covariate values for original cameras in data} 

#select unique values for each camera
ada_pred <- GAMM.df %>% select(unique_id, brand, cover, shrub, canopy)

#filter down to only unique 
ada_pred <- unique(ada_pred)

#repeat each unique camera 840 times (20x40 grid size)
ada_pred <- ada_pred[rep(seq_len(nrow(ada_pred)), each = 840), ]

#order data by unique_id
ada_pred <- arrange(ada_pred, unique_id)

#generate spatial values for each camera
#y / grid / perpendicular dist distances?
runs <- seq(from = -10, to = 10, by = 1)
grid_dist <- rep(runs, times = 40)
#rep 37 times fro 37 cameras
ada_pred$grid_dist <- rep(grid_dist, times=37)
#seconds since, assume camera just took a photo
ada_pred$seconds_since <- rep(1, times =)

# parallel distance, want to predict to 40m, since cameras cant reach that far
x_distance <- rep(1:40, each = 21)
#rep 37 times for 37 cameras
ada_pred$x_distance <- rep(x_distance, times =37)

#fill with mean values
ada_pred$temp <- rep(base::mean(GAMM.df$temp), times=)
ada_pred$velocity <- rep(base::mean(GAMM.df$velocity), times=)

#predict prob of capture of each cell on the logit link scale, back transform
ada_pred$prediction <- predict_gamm(total_mod, ada_pred, type = "link", 
                                    se.fit = TRUE, re_form =  NA)

#mean back transformation
ada_pred$mean <- (exp(ada_pred$prediction$prediction.fit)) /
                        (1 + (exp(ada_pred$prediction$prediction.fit)))


ada_pred$lower <- exp(ada_pred$prediction$prediction.fit - 
                     (ada_pred$prediction$prediction.se.fit)) /
                      (1 + exp(ada_pred$prediction$prediction.fit - 
                                 (ada_pred$prediction$prediction.se.fit)))

ada_pred$upper <- exp(ada_pred$prediction$prediction.fit 
                      + (ada_pred$prediction$prediction.se.fit)) /
                      (1 + exp(ada_pred$prediction$prediction.fit 
                      + (ada_pred$prediction$prediction.se.fit)))
  

#group by unique_ID and sum to get ADA
ada_results <- ada_pred %>%
     group_by(unique_id) %>% 
    summarise(eca = base::sum(mean),lower = base::sum(lower), upper = base::sum(upper))
```

```{r, Generating a single camera for plotting}
#Reconyx brand cameras

#parallel and perpendicular distances
runs <- seq(from = -10, to = 10, by = 1)
grid_dist <- rep(runs, times = 40)
# want to predict to 40m, since cameras cant reach that far
x_distance <- rep(1:40, each = 21)
#cover (average % in field)
shrub <-  rep(base::mean(GAMM.df$shrub), times = 840)
#cover
cover <- rep(base::mean(GAMM.df$cover), times=840)
#mean temp during survey time
temp <-  rep(base::mean(GAMM.df$temp), times = 840)
#velocity, based of how fast we were moving
velocity <- rep(base:: mean(GAMM.df$velocity), times = 840)
#brand 
brand <- rep("reconyx", times = 840)
#seconds since 
seconds_since <- rep(1, times=840)
#unique_id
unique_id <- rep("RM-1-1", times=840)
#new df of all preds.
heat_df <- cbind.data.frame(grid_dist,x_distance,shrub,temp,velocity,brand,cover,unique_id)

#using simulated grid to predict probability of photographic capture in 1x1m cells
heat_df$pred <- gammit::predict_gamm(total_mod, heat_df, 
                  re_form = NA, se.fit =TRUE, type = "link")

#mean back transformation
heat_df$mean <- (exp(heat_df$pred$prediction.fit)) /
                        (1 + (exp(heat_df$pred$prediction.fit)))


heat_df$lower <- exp(heat_df$pred$prediction.fit - 
                     (heat_df$pred$prediction.se.fit)) /
                      (1 + exp(heat_df$pred$prediction.fit - 
                                 (heat_df$pred$prediction.se.fit)))

heat_df$upper <- exp(heat_df$pred$prediction.fit 
                      + (heat_df$pred$prediction.se.fit)) /
                      (1 + exp(heat_df$pred$prediction.fit 
                      + (heat_df$pred$prediction.se.fit)))

base::sum(heat_df$mean) #mean ECA prediction 14.71432
base::sum(heat_df$lower) #lower credible interval 5.13024
base::sum(heat_df$upper) #upper credible interval76.11202
```

```{r, plotting the ADA into a heat map}
ggplot(heat_df) +
  geom_tile(aes(x = grid_dist, y = x_distance, fill = mean, alpha = is.na(mean))) +
  coord_equal() +
  scale_alpha_manual(values = c('TRUE' = 0, 'FALSE' = 1)) +
  guides(alpha = 'none') +
  labs(x = '', y = '') +
  scale_fill_gradient2(low = "blue", high = "orange", mid = "lightsalmon", midpoint = 0.3) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
     xlab("Location (m) perpendicular to camera trap") +
  ylab("Location (m) parallel  to camera trap")+
  theme(text=element_text(size=12, colour = "black")) +
  theme(axis.title.x=element_text(size=12, colour = "black")) +
  theme(axis.title.y=element_text(size=12, colour = "black")) +
  labs(fill = "Probability of 
    capture") +
  theme_bw() 

#ggsave("rex_ada.pdf")
```

```{r how numeric variables (shrub, cover, temperature, velocity) influence ECA size}
# Shrub
#parallel and perpendicular distances
runs <- seq(from = -10, to = 10, by = 1)
grid_dist <- rep(runs, times = 7080)
# want to predict to 40m, since cameras cant reach that far
x_distance <- rep(1:40, each = 3717)
#shrub (cover, temperature, velocity)
base::min(GAMM.df$shrub)
base::max(GAMM.df$shrub)
shrub <- rep(0:176, each = 840)
#random ID 
unique_id <- rep("RM-99-99", times = 148680)
#cover
cover <- rep(base::mean(GAMM.df$cover), times=148680)
#mean temp during survey time
temp <-  rep(base::mean(GAMM.df$temp), times = 148680)
#velocity, based of how fast we were moving
velocity <- rep(base:: mean(GAMM.df$velocity), times = 148680)
#brand 
brand <- rep("reconyx", times = 148680)
#seconds since 
seconds_since <- rep(1, times=148680)

shrub_es <- cbind.data.frame(unique_id,grid_dist,x_distance,shrub,cover,velocity,
                             brand,seconds_since,temp)

shrub_es$prediction <- predict_gamm(total_mod, shrub_es, type = "link", 
                          se.fit = TRUE, re_form =  NA, 
                          exclude = c("cover", "temp", "velocity", "brand", "seconds_since"))

#transform back to responce scale
shrub_es$mean <- (exp(shrub_es$pred$prediction.fit)) /
                        (1 + (exp(shrub_es$pred$prediction.fit)))


shrub_es$lower <- exp(shrub_es$pred$prediction.fit - 
                     (shrub_es$pred$prediction.se.fit)) /
                      (1 + exp(shrub_es$pred$prediction.fit - 
                                 (shrub_es$pred$prediction.se.fit)))

shrub_es$upper <- exp(shrub_es$pred$prediction.fit 
                      + (shrub_es$pred$prediction.se.fit)) /
                      (1 + exp(shrub_es$pred$prediction.fit 
                      + (shrub_es$pred$prediction.se.fit)))

#group by iteration of shrub range (i.e., 0 - 100)
shrub_r <- shrub_es %>% 
            group_by(shrub) %>%
            reframe(mean = base::sum(mean), lower = base::sum(lower), upper = base::sum(upper))
    
#mean influence of change in unit value 
abs(base::mean(diff(shrub_r$mean))) #0.2110967

s <- ggplot(shrub_r) +
  geom_point(aes(x=shrub,y=mean)) +
  xlab("Percent shrub cover") + ylab("") + ylim(0,90) +
  theme(axis.title=element_text(size=13, colour = "black")) +
  theme(axis.text=element_text(size=13, colour = "black")) +
  theme_minimal()
```

```{r how numeric variables (shrub, cover, temperature, velocity) influence ECA size}
# Cover
#parallel and perpendicular distances
runs <- seq(from = -10, to = 10, by = 1)
grid_dist <- rep(runs, times = 2320)
# want to predict to 40m, since cameras cant reach that far
x_distance <- rep(1:40, each = 1218)
#cover ranges
base::min(GAMM.df$cover)
base::max(GAMM.df$cover)
cover <- rep(42:99, each = 840)
#random ID 
unique_id <- rep("RM-99-99", times = 48720)
#shrub
shrub <- rep(base::mean(GAMM.df$shrub), times=48720)
#mean temp during survey time
temp <-  rep(base::mean(GAMM.df$temp), times = 48720)
#velocity, based of how fast we were moving
velocity <- rep(base:: mean(GAMM.df$velocity), times = 48720)
#brand 
brand <- rep("reconyx", times = 48720)
#seconds since 
seconds_since <- rep(1, times=48720)

cover_es <- cbind.data.frame(unique_id,grid_dist,x_distance,shrub,cover,velocity,
                             brand,seconds_since,temp)

cover_es$prediction <- predict_gamm(total_mod, cover_es, type = "link", 
                          se.fit = TRUE, re_form =  NA, 
                          exclude = c("shrub", "temp", "velocity", "brand", "seconds_since"))

#transform back to responce scale
cover_es$mean <- (exp(cover_es$pred$prediction.fit)) /
                        (1 + (exp(cover_es$pred$prediction.fit)))


cover_es$lower <- exp(cover_es$pred$prediction.fit - 
                     (cover_es$pred$prediction.se.fit)) /
                      (1 + exp(cover_es$pred$prediction.fit - 
                                 (cover_es$pred$prediction.se.fit)))

cover_es$upper <- exp(cover_es$pred$prediction.fit 
                      + (cover_es$pred$prediction.se.fit)) /
                      (1 + exp(cover_es$pred$prediction.fit 
                      + (cover_es$pred$prediction.se.fit)))

#group by iteration of shrub range (i.e., 0 - 100)
cover_r <- cover_es %>% 
            group_by(cover) %>%
            reframe(mean = base::sum(mean), lower = base::sum(lower), upper = base::sum(upper))
    
#mean influence of change in unit value 
abs(base::mean(diff(cover_r$mean))) #0.2134891

c <- ggplot(cover_r) +
  geom_point(aes(x=cover,y=mean)) + 
  xlab("Percent horizontal cover of vegetation") + ylab("") + ylim(0,90) +
   theme(axis.title=element_text(size=13, colour = "black")) +
  theme(axis.text=element_text(size=13, colour = "black")) +
  theme_minimal()
```

```{r how numeric variables (shrub, cover, temperature, velocity) influence ECA size}
# Temp
#parallel and perpendicular distances
runs <- seq(from = -10, to = 10, by = 1)
grid_dist <- rep(runs, times = 520)
# want to predict to 40m, since cameras cant reach that far
x_distance <- rep(1:40, each = 273)
#shrub (cover, temperature, velocity)
cover <- rep(base::mean(GAMM.df$cover), times=10920)
#random ID 
unique_id <- rep("RM-99-99", times = 10920)
#cover
shrub <- rep(base::mean(GAMM.df$shrub), times=10920)
#mean temp during survey time
base::min(GAMM.df$temp) #-2
base::max(GAMM.df$temp) #10
temp <-  rep(-2:10, each = 840)
#velocity, based of how fast we were moving
velocity <- rep(base:: mean(GAMM.df$velocity), times = 10920)
#brand 
brand <- rep("reconyx", times = 10920)
#seconds since 
seconds_since <- rep(1, times=10920)

temp_es <- cbind.data.frame(unique_id,grid_dist,x_distance,shrub,cover,velocity,
                             brand,seconds_since,temp)

temp_es$prediction <- predict_gamm(total_mod, temp_es, type = "link", 
                          se.fit = TRUE, re_form =  NA, 
                          exclude = c("shrub", "cover", "velocity", "brand", "seconds_since"))

#transform back to responce scale
temp_es$mean <- (exp(temp_es$pred$prediction.fit)) /
                        (1 + (exp(temp_es$pred$prediction.fit)))


temp_es$lower <- exp(temp_es$pred$prediction.fit - 
                     (temp_es$pred$prediction.se.fit)) /
                      (1 + exp(temp_es$pred$prediction.fit - 
                                 (temp_es$pred$prediction.se.fit)))

temp_es$upper <- exp(temp_es$pred$prediction.fit 
                      + (temp_es$pred$prediction.se.fit)) /
                      (1 + exp(temp_es$pred$prediction.fit 
                      + (temp_es$pred$prediction.se.fit)))

#group by iteration of shrub range (i.e., 0 - 100)
temp_r <- temp_es %>% 
            group_by(temp) %>%
            reframe(mean = base::sum(mean), lower = base::sum(lower), upper = base::sum(upper))
    
#mean influence of change in unit value 
abs(base::mean(diff(temp_r$mean))) #2.546237

t <- ggplot(temp_r) +
  geom_point(aes(x=temp,y=mean)) + 
  xlab("Ambient temperature (\u00B0C)") + ylab("") + ylim(0,90) +
   theme(axis.title=element_text(size=13, colour = "black")) +
  theme(axis.text=element_text(size=13, colour = "black")) +
  theme_minimal()
```

```{r how numeric variables (shrub, cover, temperature, velocity) influence ECA size}
#velocity 
#parallel and perpendicular distances
runs <- seq(from = -10, to = 10, by = 1)
grid_dist <- rep(runs, times = 120)
# want to predict to 40m, since cameras cant reach that far
x_distance <- rep(1:40, each = 63)
#shrub (cover, temperature, velocity)
cover <- rep(base::mean(GAMM.df$cover), times=2520)
#random ID 
unique_id <- rep("RM-99-99", times = 2520)
#cover
shrub <- rep(base::mean(GAMM.df$shrub), times=2520)
#mean temp during survey time
temp <-  rep(base::mean(GAMM.df$temp), times = 2520)
#velocity, based of how fast we were moving
base::min(GAMM.df$velocity)
base::max(GAMM.df$velocity)
velocity <- rep(1:3, each = 840)
#brand 
brand <- rep("reconyx", times = 2520)
#seconds since 
seconds_since <- rep(1, times=2520)

velocity_es <- cbind.data.frame(unique_id,grid_dist,x_distance,shrub,cover,velocity,
                             brand,seconds_since,temp)

velocity_es$prediction <- predict_gamm(total_mod, velocity_es, type = "link", 
                          se.fit = TRUE, re_form =  NA, 
                          exclude = c("shrub", "cover", "temp", "brand", "seconds_since"))

#transform back to responce scale
velocity_es$mean <- (exp(velocity_es$pred$prediction.fit)) /
                        (1 + (exp(velocity_es$pred$prediction.fit)))


velocity_es$lower <- exp(velocity_es$pred$prediction.fit - 
                     (velocity_es$pred$prediction.se.fit)) /
                      (1 + exp(velocity_es$pred$prediction.fit - 
                                 (velocity_es$pred$prediction.se.fit)))

velocity_es$upper <- exp(velocity_es$pred$prediction.fit 
                      + (velocity_es$pred$prediction.se.fit)) /
                      (1 + exp(velocity_es$pred$prediction.fit 
                      + (velocity_es$pred$prediction.se.fit)))

#group by iteration of shrub range (i.e., 0 - 100)
velocity_r <- velocity_es %>% 
            group_by(velocity) %>%
            reframe(mean = base::sum(mean), lower = base::sum(lower), upper = base::sum(upper))
    
#mean influence of change in unit value 
abs(base::mean(diff(velocity_r$mean))) #34.62955


v <- ggplot() +
  geom_line(data = velocity_r, aes(x=velocity,y=mean)) + 
  xlab("Velocity (m/s) of each jog") + ylab("") + ylim(0,90) +
   theme(axis.title=element_text(size=13, colour = "black")) +
  theme(axis.text=element_text(size=13, colour = "black")) +
  theme_minimal()
```

```{r multipannel plot of post hoc effect sizes}

#positions
lay <- rbind(c(1,1,2,2),
             c(3,3,4,4))

figure <- grid.arrange(s,c,t,v, layout_matrix = lay)

annotate_figure(figure, left = text_grob(bquote("Effective capture area" ~(m^2)), 
                color = "black", size = 14, rot = 90), 
                bottom = text_grob("Unit changes in numerical covariates", 
                                   color = "black", size = 14))

ggsave("effects.pdf", width = 11.5, height = 8)

```

```{r, Cross validation, accuracy of predicting capture probability across cams where jog-tests didnt happen}

#Running the models many times, each time withholding a single camera 
c_16_9 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-16-9',])

c_14_9 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-14-9',])

c_19_9 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-19-9',])

c_30_9 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-30-9',])

c_4_9 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-4-9',])

c_6_9 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-6-9',])

c_8_9 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-8-9',])

c_14_1 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-14-1',])

c_14_2 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-14-2',])

c_14_3 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-14-3',])

c_14_4 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-14-4',])

c_14_5 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-14-5',])

c_14_7 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-14-7',])

c_14_8 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-14-8',])

c_16_1 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-16-1',])

c_16_6 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-16-6',])

c_16_7 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-16-7',])

c_19_4 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-19-4',])

c_19_6 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-19-6',])

c_30_1 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-30-1',])

c_30_8 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-30-8',])

c_4_1 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-4-1',])

c_4_2 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-4-2',])

c_4_4 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-4-4',])

c_4_6 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-4-6',])

c_4_8 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-4-8',])

c_6_1 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-6-1',])

c_6_3 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-6-3',])

c_6_5 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-6-5',])

c_6_6 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-6-6',])

c_6_7 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-6-7',])

c_6_8 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-6-8',])

c_8_1 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-8-1',])

c_8_4 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-8-4',])

c_8_5 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-8-5',])

c_8_7 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-8-7',])

c_8_8 <- gam(detection ~ s(x_distance, grid_dist, bs='gp') 
                + te(shrub, cover)
                + brand + as.factor(seconds_since) + temp + velocity
                + s(unique_id, bs='fs'), 
                family = 'binomial', data = GAMM.df[GAMM.df$unique_id != 'RM-8-8',])

AUC_df <-  GAMM.df

#now predict each withheld camera, from each withheld model, and attach to new DF
pred_14_9 <- predict_gamm(c_14_9$gam, AUC_df[AUC_df$unique_id == "RM-14-9",],re_form = NA, type = "link")
pred_16_9 <- predict_gamm(c_16_9$gam, AUC_df[AUC_df$unique_id == "RM-16-9",],re_form = NA, type = "link")
pred_19_9 <- predict_gamm(c_19_9$gam, AUC_df[AUC_df$unique_id == "RM-19-9",],re_form = NA, type = "link")
pred_30_9 <- predict_gamm(c_30_9$gam, AUC_df[AUC_df$unique_id == "RM-30-9",],re_form = NA, type = "link")
pred_4_9 <- predict_gamm(c_4_9$gam, AUC_df[AUC_df$unique_id == "RM-4-9",],re_form = NA, type = "link")
pred_6_9 <- predict_gamm(c_6_9$gam, AUC_df[AUC_df$unique_id == "RM-6-9",],re_form = NA, type = "link")
pred_8_9 <- predict_gamm(c_8_9$gam, AUC_df[AUC_df$unique_id == "RM-8-9",],re_form = NA, type = "link")
pred_14_1 <- predict_gamm(c_14_1$gam, AUC_df[AUC_df$unique_id == "RM-14-1",],re_form = NA, type = "link")
pred_14_2 <- predict_gamm(c_14_2$gam, AUC_df[AUC_df$unique_id == "RM-14-2",],re_form = NA, type = "link")
pred_14_3 <- predict_gamm(c_14_3$gam, AUC_df[AUC_df$unique_id == "RM-14-3",],re_form = NA, type = "link")
pred_14_4 <- predict_gamm(c_14_4$gam, AUC_df[AUC_df$unique_id == "RM-14-4",],re_form = NA, type = "link")
pred_14_5 <- predict_gamm(c_14_5$gam, AUC_df[AUC_df$unique_id == "RM-14-5",],re_form = NA, type = "link")
pred_14_7 <- predict_gamm(c_14_7$gam, AUC_df[AUC_df$unique_id == "RM-14-7",],re_form = NA, type = "link")
pred_14_8 <- predict_gamm(c_14_8$gam, AUC_df[AUC_df$unique_id == "RM-14-8",],re_form = NA, type = "link")
pred_16_1 <- predict_gamm(c_16_1$gam, AUC_df[AUC_df$unique_id == "RM-16-1",],re_form = NA, type = "link")
pred_16_6 <- predict_gamm(c_16_6$gam, AUC_df[AUC_df$unique_id == "RM-16-6",],re_form = NA, type = "link")
pred_16_7 <- predict_gamm(c_16_7$gam, AUC_df[AUC_df$unique_id == "RM-16-7",],re_form = NA, type = "link")
pred_19_4 <- predict_gamm(c_19_4$gam, AUC_df[AUC_df$unique_id == "RM-19-4",],re_form = NA, type = "link")
pred_19_6 <- predict_gamm(c_19_6$gam, AUC_df[AUC_df$unique_id == "RM-19-6",],re_form = NA,type = "link")
pred_30_1 <- predict_gamm(c_30_1$gam, AUC_df[AUC_df$unique_id == "RM-30-1",],re_form = NA, type = "link")
pred_30_8 <- predict_gamm(c_30_8$gam, AUC_df[AUC_df$unique_id == "RM-30-8",],re_form = NA, type = "link")
pred_4_1 <- predict_gamm(c_4_1$gam, AUC_df[AUC_df$unique_id == "RM-4-1",],re_form = NA, type = "link")
pred_4_2 <- predict_gamm(c_4_2$gam, AUC_df[AUC_df$unique_id == "RM-4-2",],re_form = NA, type = "link")
pred_4_4 <- predict_gamm(c_4_4$gam, AUC_df[AUC_df$unique_id == "RM-4-4",],re_form = NA, type = "link")
pred_4_6 <- predict_gamm(c_4_6$gam, AUC_df[AUC_df$unique_id == "RM-4-6",],re_form = NA, type = "link")
pred_4_8 <- predict_gamm(c_4_8$gam, AUC_df[AUC_df$unique_id == "RM-4-8",],re_form = NA, type = "link")
pred_6_1 <- predict_gamm(c_6_1$gam, AUC_df[AUC_df$unique_id == "RM-6-1",],re_form = NA, type = "link")
pred_6_3 <- predict_gamm(c_6_3$gam, AUC_df[AUC_df$unique_id == "RM-6-3",],re_form = NA, type = "link")
pred_6_5 <- predict_gamm(c_6_5$gam, AUC_df[AUC_df$unique_id == "RM-6-5",],re_form = NA, type = "link")
pred_6_6 <- predict_gamm(c_6_6$gam, AUC_df[AUC_df$unique_id == "RM-6-6",],re_form = NA, type = "link")
pred_6_7 <- predict_gamm(c_6_7$gam, AUC_df[AUC_df$unique_id == "RM-6-7",],re_form = NA, type = "link")
pred_6_8 <- predict_gamm(c_6_8$gam, AUC_df[AUC_df$unique_id == "RM-6-8",],re_form = NA, type = "link")
pred_8_1 <- predict_gamm(c_8_1$gam, AUC_df[AUC_df$unique_id == "RM-8-1",],re_form = NA, type = "link")
pred_8_4 <- predict_gamm(c_8_4$gam, AUC_df[AUC_df$unique_id == "RM-8-4",],re_form = NA, type = "link")
pred_8_5 <- predict_gamm(c_8_5$gam, AUC_df[AUC_df$unique_id == "RM-8-5",],re_form = NA, type = "link")
pred_8_7 <- predict_gamm(c_8_7$gam, AUC_df[AUC_df$unique_id == "RM-8-7",],re_form = NA, type = "link")
pred_8_8 <- predict_gamm(c_8_8$gam, AUC_df[AUC_df$unique_id == "RM-8-8",],re_form = NA, type = "link")

#needs to be in a DF format
pred_14_9 <- as.data.frame(pred_14_9)
pred_16_9 <- as.data.frame(pred_16_9)
pred_19_9 <- as.data.frame(pred_19_9)
pred_30_9 <- as.data.frame(pred_30_9)
pred_4_9 <- as.data.frame(pred_4_9)
pred_6_9 <- as.data.frame(pred_6_9)
pred_8_9 <- as.data.frame(pred_8_9)
pred_14_1 <- as.data.frame(pred_14_1)
pred_14_2 <- as.data.frame(pred_14_2)
pred_14_3 <- as.data.frame(pred_14_3)
pred_14_4 <- as.data.frame(pred_14_4)
pred_14_5 <-as.data.frame(pred_14_5)
pred_14_7 <- as.data.frame(pred_14_7)
pred_14_8 <- as.data.frame(pred_14_8)
pred_16_1 <- as.data.frame(pred_16_1)
pred_16_6 <- as.data.frame(pred_16_6)
pred_16_7 <- as.data.frame(pred_16_7)
pred_19_4 <- as.data.frame(pred_19_4)
pred_19_6 <- as.data.frame(pred_19_6)
pred_30_1 <- as.data.frame(pred_30_1)
pred_30_8 <- as.data.frame(pred_30_8)
pred_4_1 <- as.data.frame(pred_4_1)
pred_4_2 <- as.data.frame(pred_4_2)
pred_4_4 <- as.data.frame(pred_4_4)
pred_4_6 <- as.data.frame(pred_4_6)
pred_4_8 <- as.data.frame(pred_4_8)
pred_6_1 <- as.data.frame(pred_6_1)
pred_6_3 <- as.data.frame(pred_6_3)
pred_6_5 <- as.data.frame(pred_6_5)
pred_6_6 <- as.data.frame(pred_6_6)
pred_6_7 <- as.data.frame(pred_6_7)
pred_6_8 <- as.data.frame(pred_6_8)
pred_8_1 <- as.data.frame(pred_8_1)
pred_8_4 <- as.data.frame(pred_8_4)
pred_8_5 <- as.data.frame(pred_8_5)
pred_8_7 <- as.data.frame(pred_8_7)
pred_8_8 <- as.data.frame(pred_8_8)

#remaning column to make consistent 
names(pred_14_9)[names(pred_14_9) == "pred_14_9"] <- "predicted_detection"
names(pred_16_9)[names(pred_16_9) == "pred_16_9"] <- "predicted_detection"
names(pred_19_9)[names(pred_19_9) == "pred_19_9"] <- "predicted_detection"
names(pred_30_9)[names(pred_30_9) == "pred_30_9"] <- "predicted_detection"
names(pred_4_9)[names(pred_4_9) == "pred_4_9"] <- "predicted_detection"
names(pred_6_9)[names(pred_6_9) == "pred_6_9"] <- "predicted_detection"
names(pred_8_9)[names(pred_8_9) == "pred_8_9"] <- "predicted_detection"
names(pred_14_1)[names(pred_14_1) == "pred_14_1"] <- "predicted_detection"
names(pred_14_2)[names(pred_14_2) == "pred_14_2"] <- "predicted_detection"
names(pred_14_3)[names(pred_14_3) == "pred_14_3"] <- "predicted_detection"
names(pred_14_4)[names(pred_14_4) == "pred_14_4"] <- "predicted_detection"
names(pred_14_5)[names(pred_14_5) == "pred_14_5"] <- "predicted_detection"
names(pred_14_7)[names(pred_14_7) == "pred_14_7"] <- "predicted_detection"
names(pred_14_8)[names(pred_14_8) == "pred_14_8"] <- "predicted_detection"
names(pred_16_1)[names(pred_16_1) == "pred_16_1"] <- "predicted_detection"
names(pred_16_6)[names(pred_16_6) == "pred_16_6"] <- "predicted_detection"
names(pred_16_7)[names(pred_16_7) == "pred_16_7"] <- "predicted_detection"
names(pred_19_4)[names(pred_19_4) == "pred_19_4"] <- "predicted_detection"
names(pred_19_6)[names(pred_19_6) == "pred_19_6"] <- "predicted_detection"
names(pred_30_1)[names(pred_30_1) == "pred_30_1"] <- "predicted_detection"
names(pred_30_8)[names(pred_30_8) == "pred_30_8"] <- "predicted_detection"
names(pred_4_1)[names(pred_4_1) == "pred_4_1"] <- "predicted_detection"
names(pred_4_2)[names(pred_4_2) == "pred_4_2"] <- "predicted_detection"
names(pred_4_4)[names(pred_4_4) == "pred_4_4"] <- "predicted_detection"
names(pred_4_6)[names(pred_4_6) == "pred_4_6"] <- "predicted_detection"
names(pred_4_8)[names(pred_4_8) == "pred_4_8"] <- "predicted_detection"
names(pred_6_1)[names(pred_6_1) == "pred_6_1"] <- "predicted_detection"
names(pred_6_3)[names(pred_6_3) == "pred_6_3"] <- "predicted_detection"
names(pred_6_5)[names(pred_6_5) == "pred_6_5"] <- "predicted_detection"
names(pred_6_6)[names(pred_6_6) == "pred_6_6"] <- "predicted_detection"
names(pred_6_7)[names(pred_6_7) == "pred_6_7"] <- "predicted_detection"
names(pred_6_8)[names(pred_6_8) == "pred_6_8"] <- "predicted_detection"
names(pred_8_1)[names(pred_8_1) == "pred_8_1"] <- "predicted_detection"
names(pred_8_4)[names(pred_8_4) == "pred_8_4"] <- "predicted_detection"
names(pred_8_5)[names(pred_8_5) == "pred_8_5"] <- "predicted_detection"
names(pred_8_7)[names(pred_8_7) == "pred_8_7"] <- "predicted_detection"
names(pred_8_8)[names(pred_8_8) == "pred_8_8"] <- "predicted_detection"

#adding unique_id for merge. times = # data points for each camera
pred_14_9$unique_id <- rep("RM-14-9", times = )
pred_16_9$unique_id <- rep("RM-16-9", times = )
pred_19_9$unique_id <- rep("RM-19-9", times = )
pred_30_9$unique_id <- rep("RM-30-9", times = )
pred_4_9$unique_id <- rep("RM-4-9", times = )
pred_6_9$unique_id <- rep("RM-6-9", times = )
pred_8_9$unique_id <- rep("RM-8-9", times = )
pred_14_1$unique_id <- rep("RM-14-1", times = )
pred_14_2$unique_id <- rep("RM-14-2", times = )
pred_14_3$unique_id <- rep("RM-14-3", times = )
pred_14_4$unique_id <- rep("RM-14-4", times = )
pred_14_5$unique_id <- rep("RM-14-5", times = )
pred_14_7$unique_id <- rep("RM-14-7", times = )
pred_14_8$unique_id <- rep("RM-14-8", times = )
pred_16_1$unique_id <- rep("RM-16-1", times = )
pred_16_6$unique_id <- rep("RM-16-6", times = )
pred_16_7$unique_id <- rep("RM-16-7", times = )
pred_19_4$unique_id <- rep("RM-19-4", times = )
pred_19_6$unique_id <- rep("RM-19-6", times = )
pred_30_1$unique_id <- rep("RM-30-1", times = )
pred_30_8$unique_id <- rep("RM-30-8", times = )
pred_4_1$unique_id <- rep("RM-4-1", times = )
pred_4_2$unique_id <- rep("RM-4-2", times = )
pred_4_4$unique_id <- rep("RM-4-4", times = )
pred_4_6$unique_id <- rep("RM-4-6", times = )
pred_4_8$unique_id <- rep("RM-4-8", times = )
pred_6_1$unique_id <- rep("RM-6-1", times = )
pred_6_3$unique_id <- rep("RM-6-3", times = )
pred_6_5$unique_id <- rep("RM-6-5", times = )
pred_6_6$unique_id <- rep("RM-6-6", times = )
pred_6_7$unique_id <- rep("RM-6-7", times = )
pred_6_8$unique_id <- rep("RM-6-8", times = )
pred_8_1$unique_id <- rep("RM-8-1", times = )
pred_8_4$unique_id <- rep("RM-8-4", times = )
pred_8_5$unique_id <- rep("RM-8-5", times = )
pred_8_7$unique_id <- rep("RM-8-6", times = )
pred_8_8$unique_id <- rep("RM-8-8", times = )

#data frame of predictions
pred_dets <- rbind.data.frame(pred_14_9,pred_16_9,pred_19_9,pred_30_9,pred_4_9,pred_6_9, pred_8_9,
                              pred_14_1,pred_14_2, pred_14_3, pred_14_4, pred_14_5, pred_14_7,
                              pred_14_8,pred_16_1,pred_16_6,pred_16_7,pred_19_4,pred_19_6,
                              pred_30_1,pred_30_8,pred_4_1,pred_4_2,pred_4_4,
                              pred_4_6,pred_4_8,pred_6_1,pred_6_3,pred_6_5,
                              pred_6_6,pred_6_7,pred_6_8,pred_8_1,pred_8_4,
                              pred_8_5,pred_8_7,pred_8_8)


#need to merge by unique_id
#first, order both AUC_df and pred_dets, then just add as new column
AUC_df <- arrange(AUC_df, unique_id)
pred_dets <- arrange(pred_dets, unique_id)

AUC_df$predicted_detection <- pred_dets$prediction

#assessing performance
rp <- prediction(AUC_df$predicted_detection, AUC_df$detection)
auc <- performance( rp, "auc")@y.values[[1]]
auc     
roc <- performance( rp, "tpr", "fpr")
print(roc)
plot(roc)
```




